version: "3.9"

services:
  backEndDeliveries:
    #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: prisma_deliveries
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma_deliveries
    volumes:
      - pgdata:/data/postgresql
volumes:
  pgdata:
    driver: local
